name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: claude-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  claude-review:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            Execute comprehensive code review for @taisei-ide-0123 in Japanese.
            
            Process:
            1. Run `gh pr diff --stat` for change overview
            2. Use `git log`, `git blame`, `grep` for context analysis
            3. Scan all modified files for issues
            4. Categorize findings: MUST/SHOULD/NICE
            5. Post single consolidated comment
            
            Output format:
            **@taisei-ide-0123**
            ### Summary
            - Files: X, Lines: +A -D, Severity: High/Med/Low
            - Concerns: [2-3 sentences]
            
            ### MUST FIX
            - [file:line] issue / reason / fix
            
            ### SHOULD FIX
            - [file:line] issue / reason / fix
            
            ### NICE TO HAVE
            - [file:line] improvement / benefit / steps
            
            ### Good Implementation
            - [positive finding with reason]
            
            ### Decision
            - Status: APPROVE|REQUEST_CHANGES|BLOCK
            - Reason: [one sentence]
            - Actions: [specific steps]
          
          claude_args: '--allowedTools "Read,Write,Edit,Grep,Find,Glob,Tree,Bash,Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr comment:*),Bash(git log:*),Bash(git show:*),Bash(git blame:*),Bash(find . -name:*),Bash(grep -r:*),Bash(cat:*),Bash(head:*),Bash(tail:*),Bash(wc:*),Bash(ls:*)" --disallowedTools "Bash(rm -rf:*),Bash(sudo:*),Bash(chmod 777:*),Bash(git commit:*),Bash(git push:*)" --model claude-sonnet-4-5-20250929'